name: Deploy Next.js App

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Use the version of Node.js compatible with your project

    # Install dependencies
    - name: Install Dependencies
      run: npm install

    # Build the project
    - name: Build Project
      run: npm run build

    # Deploy to server
    - name: Deploy to Server
      env:
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
      run: |
        sshpass -p "$SERVER_PASSWORD" ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_HOST "
          cd /path/to/your/project &&
          git pull origin main &&
          npm install &&
          npm run build &&
          sudo systemctl restart nextjs-app
        "
